### ISSUE TITLE
DRM Dumper, Can't convert textures, Marvel Avengers

### ISSUE THREAD

**Issue by Tosyk** [Ekey/CDCE.TIGER.Tool#2]
Hi,

I can't seem to dump textures properly. Happen to both ULTRA texture archive and NORMAL ones. Can you help with this?
Described it here in details.

But in short, when I used noesis to convert MAPCD files dumped I get:
`Fatal Error: Unknown file magic: 0x82017f80 expected PCD!
Detected file type: Unknown`

**Comment by Ekey** [comment]
Probably the archives were decrypted incorrectly or something changed in stuctures. Anyway, I don't have this game to check it.

**Comment by Tosyk** [comment]
thanks for the reply. Nothing to the archives been changed according to the tool version of yours which is work
https://forum.xentax.com/viewtopic.php?p=181904#p181904
