### ISSUE TITLE
How to get the hash list for the updated version?

### ISSUE THREAD

**Issue by reitowo** [Ekey/CDCE.TIGER.Tool#3]
Is there any way to get the latest file hash list? By brute forcing?

**Comment by Ekey** [comment]
There are many ways to get names

1. - Hooking hash function.
2. - Exploring files manually.

**Comment by 0x-raafet** [comment]
Sorry there no issues but i want ask you how hash algorithm work in conflict series that developed by pivotal games do you hook hash function when you developed CE.UNPACKER
